cuda_compiler:
  - cuda-nvcc

c_compiler:
  - gcc      # [linux]
  - vs2022   # [win]

cxx_compiler:
  - gxx      # [linux]
  - vs2022   # [win]

c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]

c_stdlib_version:              # [linux]
  - 2.17                       # [linux]

tensorrt_version:
  - 8.6
  - 10.0

# TODO: nvcc bug
c_compiler_version:     # [win]
  - 19.39               # [win]

cxx_compiler_version:   # [win]
  - 19.39               # [win]